services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:smx
    volumes: 
      - wp_db:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:smx
    depends_on:
      - mariadb
      - redis
    volumes: 
      - wp_files:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx:smx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes: 
      - wp_files:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
#bonus redis
  redis:
    build: ./bonus/redis
    container_name: redis
    image: redis:smx
    networks:
      - inception
    restart: on-failure
#bonus ftp
  ftp:
      build: ./bonus/ftp
      container_name: ftp
      image: ftp:smx
      depends_on:
        - wordpress
      ports:
        - "21:21"
        - "11110-11111:11110-11111"
      volumes:
        - wp_files:/var/www/html
      networks:
        - inception
      env_file:
        - .env
      restart: on-failure
#bonus static website
  website:
    build: ./bonus/website
    container_name: website
    image: website:smx
    ports:
      - "1111:80"
    networks:
      - inception
    restart: on-failure
#bonus adminer
  adminer:
    build: ./bonus/adminer
    container_name: adminer
    image: adminer:smx
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
      - inception
    restart: on-failure
#bonus container monitor
  portainer:
    build: ./bonus/portainer
    container_name: portainer
    image: portainer:smx
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - inception
    restart: on-failure
volumes:
  wp_files:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/selbouka/data/wordpress
  wp_db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/selbouka/data/mariadb
# bonus
  portainer_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/selbouka/data/portainer
networks:
  inception:
    driver: bridge
